apiVersion: v1
kind: Secret      #Tells Kubernetes this is a Secret resource.Kubernetes stores it encrypted.
metadata:
  name: hello-k8s-secret
type: Opaque      #most common secret type, used for arbitrary key-value pairs.
data:
  DB_PASSWORD: amlqYXNoMDAwMA==
  API_KEY: amlqYXNoa29hcGk=


#other tyoes of secrets:
# type: kubernetes.io/dockerconfigjson  #used for storing Docker registry credentials.